"""Initial migration

Revision ID: 7835d3211c5c
Revises:
Create Date: 2026-08-18 14:32:05.369577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7835d3211c5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('source_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('destination_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('source_port', sa.INTEGER(), nullable=True),
    sa.Column('destination_port', sa.INTEGER(), nullable=True),
    sa.Column('protocol', sa.VARCHAR(length=20), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user', sa.VARCHAR(length=255), nullable=True),
    sa.Column('asset', sa.VARCHAR(length=255), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('raw_data', sqlite.JSON(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=1)
    op.create_table('threat_intel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('indicator', sa.VARCHAR(length=255), nullable=False),
    sa.Column('indicator_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('threat_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('first_seen', sa.DATETIME(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('expired_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_indicator'), 'threat_intel', ['indicator'], unique=False)
    op.create_index(op.f('ix_threat_intel_id'), 'threat_intel', ['id'], unique=False)
    op.create_table('incident_ai_analyses',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('incident_id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('analysis', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('detections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('detection_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rule_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('risk_score', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('source_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('destination_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user', sa.VARCHAR(length=255), nullable=True),
    sa.Column('asset', sa.VARCHAR(length=255), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('event_ids', sqlite.JSON(), nullable=True),
    sa.Column('evidence', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    op.create_index(op.f('ix_detections_rule_id'), 'detections', ['rule_id'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_detections_detection_id'), 'detections', ['detection_id'], unique=1)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cve_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('published_date', sa.DATETIME(), nullable=True),
    sa.Column('modified_date', sa.DATETIME(), nullable=True),
    sa.Column('cvss_score', sa.INTEGER(), nullable=True),
    sa.Column('affected_software', sqlite.JSON(), nullable=True),
    sa.Column('references', sqlite.JSON(), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=1)
    op.create_table('incident_asset',
    sa.Column('incident_id', sa.INTEGER(), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], )
    )
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('hostname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('mac_address', sa.VARCHAR(length=17), nullable=True),
    sa.Column('asset_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('operating_system', sa.VARCHAR(length=255), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('is_critical', sa.BOOLEAN(), nullable=True),
    sa.Column('is_monitored', sa.BOOLEAN(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=1)
    op.create_table('event_threat_intel',
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('threat_intel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['threat_intel_id'], ['threat_intel.id'], )
    )
    op.create_table('detection_incident',
    sa.Column('detection_id', sa.INTEGER(), nullable=True),
    sa.Column('incident_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], )
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=1)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('technique_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tactic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('data_sources', sqlite.JSON(), nullable=True),
    sa.Column('platforms', sqlite.JSON(), nullable=True),
    sa.Column('permissions_required', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_technique_id'), 'mitre_techniques', ['technique_id'], unique=1)
    op.create_index(op.f('ix_mitre_techniques_id'), 'mitre_techniques', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('reported_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('risk_score', sa.INTEGER(), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('timeline', sqlite.JSON(), nullable=True),
    sa.Column('raw_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=1)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('incident_mitre_technique',
    sa.Column('incident_id', sa.INTEGER(), nullable=True),
    sa.Column('mitre_technique_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['mitre_technique_id'], ['mitre_techniques.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_mitre_technique')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_mitre_techniques_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_technique_id'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('detection_incident')
    op.drop_table('event_threat_intel')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('incident_asset')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_detections_detection_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_rule_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_table('detections')
    op.drop_table('user_roles')
    op.drop_table('incident_ai_analyses')
    op.drop_index(op.f('ix_threat_intel_id'), table_name='threat_intel')
    op.drop_index(op.f('ix_threat_intel_indicator'), table_name='threat_intel')
    op.drop_table('threat_intel')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
